Repository jeertmans/manim-slides, pull requests merged in 2022-11, with the labels that each got.

#64 feat(cli): add app icon
  manim-slides.qrc
  manim_slides/present.py
  manim_slides/resources.py
  manim_slides/wizard.py
  pyproject.toml
  static/icon.png
Labels: enhancement

#66 feat(cli): add convert option to generate html presentations
  .github/workflows/pages.yml
  .github/workflows/test_examples.yml
  .gitignore
  docs/source/index.rst
  example.py
  manim_slides/commons.py
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/defaults.py
  manim_slides/main.py
  manim_slides/present.py
  manim_slides/slide.py
Labels: enhancement

#69 fix(ci): setup minimal python version for flake8
  .flake8
Labels: ci

#70 Remove redundant black hook & specify minimal supported python version for hooks
  .pre-commit-config.yaml
Labels: ci

#74 chore(python): support and tests for Python 3.11
  .github/workflows/test_examples.yml
  setup.py
Labels: ci

#68 Fix flake8 check errors: unused imports, tab warning
  .github/workflows/test_examples.yml
  example.py
  manim_slides/convert.py
  manim_slides/data/revealjs_template.html
  manim_slides/defaults.py
  manim_slides/present.py
  setup.py
Labels: ci

#75 chore(lib): add missing type hints and mypy is happy!
  .pre-commit-config.yaml
  manim_slides/commons.py
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present.py
  manim_slides/slide.py
  manim_slides/wizard.py
Labels: documentation, ci

#78 chore(setup): move setup config to pyproject.toml
  .github/workflows/python-publish.yml
  pyproject.toml
  setup.py
Labels: ci
