Repository jeertmans/manim-slides, pull requests merged in 2022-10, with the labels that each got.

#32 chore(ci): add more style checks
  .flake8
  .pre-commit-config.yaml
  example.py
  manim_slides/__init__.py
  manim_slides/manim.py
  manim_slides/present.py
  manim_slides/slide.py
  static/logo.py
Labels: enhancement

#43 Added Pull Request Template
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#46 Update defaults.py
  manim_slides/defaults.py
Labels: enhancement, hacktoberfest-accepted

#41 chore(ci): pre-commit mypy
  .pre-commit-config.yaml
  docs/source/conf.py
  example.py
  manim_slides/defaults.py
  manim_slides/manim.py
  manim_slides/present.py
  manim_slides/slide.py
  setup.py
  static/logo.py
Labels: hacktoberfest-accepted

#50 feat(cli): add basic logging facilities
  manim_slides/commons.py
  manim_slides/config.py
  manim_slides/present.py
  manim_slides/wizard.py
Labels: enhancement

#49 refactor: use PyQT5 for window display
  .github/workflows/test_examples.yml
  .pre-commit-config.yaml
  manim_slides/config.py
  manim_slides/defaults.py
  manim_slides/main.py
  manim_slides/manim.py
  manim_slides/present.py
  manim_slides/slide.py
  manim_slides/wizard.py
  setup.py
Labels: enhancement, help wanted

#56 Mouse Show/Hide feature
  manim_slides/config.py
  manim_slides/present.py
Labels: enhancement

#59 feat(cli): add resize mode option
  manim_slides/config.py
  manim_slides/present.py
Labels: enhancement

#60 feat: add option for background color
  manim_slides/present.py
Labels: enhancement

#61 chore(cli): change metavar for some options
  manim_slides/commons.py
  manim_slides/present.py
Labels: documentation

#62 refactor(lib): change PyQT5 to PySide6
  README.md
  manim_slides/config.py
  manim_slides/present.py
  manim_slides/wizard.py
  setup.py
Labels: enhancement

#63 feat(cli): read environ variable for verbosity
  .github/workflows/pages.yml
  .github/workflows/test_examples.yml
  manim_slides/commons.py
Labels: enhancement
