Repository jeertmans/manim-slides, pull requests merged in 2023-01, with the labels that each got.

#101 fix(convert): correctly quote paths when using ffmpeg on Windows
  manim_slides/config.py
Labels: bug

#103 chore(lint): remove flake8 in favor to ruff
  .flake8
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: ci

#112 fix(ci): build docs using poetry env
  .github/workflows/pages.yml
Labels: bug, documentation, ci

#113 chore(ci): improve docs build
  .github/workflows/pages.yml
Labels: documentation, ci

#114 chore(ci): add yaml and toml formatters
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/support.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/languagetool.yml
  .github/workflows/pages.yml
  .github/workflows/python-publish.yml
  .github/workflows/test_examples.yml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: ci

#115 chore(docs): improving the docs
  .github/workflows/pages.yml
  .github/workflows/test_examples.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/contributing/index.md
  docs/source/contributing/internals.md
  docs/source/contributing/workflow.md
  docs/source/index.md
  docs/source/index.rst
  docs/source/license.md
  docs/source/quickstart.md
  docs/source/reference/api.md
  docs/source/reference/cli.md
  docs/source/reference/examples.md
  docs/source/reference/index.md
  example.py
  manim_slides/slide.py
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, ci

#117 feat(lib): remove constraint on last animation and update readme
  README.md
  example.py
  manim_slides/slide.py
Labels: documentation, enhancement

#116 chore(docs): improving the docs a bit more
  docs/source/conf.py
  docs/source/reference/examples.md
  manim_slides/slide.py
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#118 chore(license): change to MIT
  LICENSE.md
  pyproject.toml
Labels: ci
