Repository jeertmans/manim-slides, pull requests merged in 2023-10, with the labels that each got.

#285 refactor(lib): change how manim API is imported
  .github/workflows/coverage.yml
  .github/workflows/tests.yml
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  custom_config.yml
  docs/source/conf.py
  docs/source/docutils.conf
  docs/source/features_table.md
  docs/source/index.md
  docs/source/manim_or_manimgl.md
  docs/source/reference/api.md
  example.py
  manim_slides/__main__.py
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/docs/manim_slides_directive.py
  manim_slides/ipython/ipython_magic.py
  manim_slides/logger.py
  manim_slides/manim.py
  manim_slides/slide.py
  manim_slides/slide/__init__.py
  manim_slides/slide/animation.py
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  manim_slides/slide/manimlib.py
  manim_slides/utils.py
  manim_slides/wizard.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/data/slides.py
  tests/data/slides/BasicSlide.json
  tests/data/slides/files/BasicSlide/05b94f634a049cd83daa9b47e483183d1ccdbc485687cee79c6ffbd4f02698da.mp4
  tests/data/slides/files/BasicSlide/05b94f634a049cd83daa9b47e483183d1ccdbc485687cee79c6ffbd4f02698da_reversed.mp4
  tests/data/slides/files/BasicSlide/275756d906c706ca0125660866bb925b8927e2b2589d31a7a578079b70076ef4.mp4
  tests/data/slides/files/BasicSlide/275756d906c706ca0125660866bb925b8927e2b2589d31a7a578079b70076ef4_reversed.mp4
  tests/data/slides/files/BasicSlide/28bf32c4df2711b07b765a647667059683133b3c45291f34692be0c845f75511.mp4
  tests/data/slides/files/BasicSlide/28bf32c4df2711b07b765a647667059683133b3c45291f34692be0c845f75511_reversed.mp4
  tests/data/slides/files/BasicSlide/5060f74bee3cb2e40a399a023e0120b3f91d348a9867c7f401db54ea337de97c.mp4
  tests/data/slides/files/BasicSlide/5060f74bee3cb2e40a399a023e0120b3f91d348a9867c7f401db54ea337de97c_reversed.mp4
  tests/data/slides/files/BasicSlide/7a5de547a0b5de2230ff3451dd680425cf0a7ea065b31e8f92b5e93527694077.mp4
  tests/data/slides/files/BasicSlide/7a5de547a0b5de2230ff3451dd680425cf0a7ea065b31e8f92b5e93527694077_reversed.mp4
  tests/data/slides/files/BasicSlide/c10cc5deb3630a8259712288913b2bd6e79d093356d379d518cc929812194bd9.mp4
  tests/data/slides/files/BasicSlide/c10cc5deb3630a8259712288913b2bd6e79d093356d379d518cc929812194bd9_reversed.mp4
  tests/data/slides/files/BasicSlide/c7d0d9ccbf764d32bf316451f2d00607b8f12893e64afe215041a8aedceeb368.mp4
  tests/data/slides/files/BasicSlide/c7d0d9ccbf764d32bf316451f2d00607b8f12893e64afe215041a8aedceeb368_reversed.mp4
  tests/data/slides/files/BasicSlide/d09707faa0d68c55e98c628c5da51d66c92d0f79ac48647526817c377f843810.mp4
  tests/data/slides/files/BasicSlide/d09707faa0d68c55e98c628c5da51d66c92d0f79ac48647526817c377f843810_reversed.mp4
  tests/test_manim.py
  tests/test_slide.py
Labels: lib

#283 chore(tests): add tests for converter methods
  manim_slides/convert.py
  tests/test_convert.py
  tests/test_main.py
Labels: hacktoberfest-accepted

#289 chore(ci): enhance current lint rules
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  manim_slides/__init__.py
  manim_slides/commons.py
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/docs/manim_slides_directive.py
  manim_slides/ipython/ipython_magic.py
  manim_slides/logger.py
  manim_slides/present/__init__.py
  manim_slides/present/player.py
  manim_slides/slide/animation.py
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  manim_slides/slide/manimlib.py
  manim_slides/utils.py
  manim_slides/wizard.py
  pyproject.toml
  tests/test_convert.py
  tests/test_slide.py
Labels: ci

#290 fix(ci): OpenGL issue on Windows server
  .github/workflows/tests.yml
  tests/test_slide.py
Labels: ci

#291 fix(lib): use optional instead of mutable defaults
  manim_slides/slide/animation.py
Labels: lib

#292 fix(convert): ClassVar was ignored by Pydantic
  manim_slides/convert.py
Labels: bug, html-convert

#294 feat(lib): add `loop` option to `next_slide` and remove `start/end_loop`
  CHANGELOG.md
  README.md
  docs/source/reference/api.md
  docs/source/reference/magic_example.ipynb
  example.py
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  tests/data/slides.py
  tests/test_slide.py
Labels: lib

#297 fix(deps): PySide6 player black screen
  poetry.lock
  pyproject.toml
Labels: dependencies, present

#300 chore(tests): adding tests for Qt widgets
  .github/workflows/tests.yml
  CHANGELOG.md
  manim_slides/present/__init__.py
  manim_slides/present/player.py
  manim_slides/qt_utils.py
  manim_slides/slide/base.py
  manim_slides/wizard.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_base_slide.py
  tests/test_defaults.py
  tests/test_main.py
  tests/test_player.py
  tests/test_present.py
  tests/test_qt_utils.py
  tests/test_slide.py
  tests/test_wizard.py
Labels: enhancement, ci

#304 feat(lib): add `auto_next` option
  .github/workflows/tests.yml
  CHANGELOG.md
  example.py
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present/player.py
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  manim_slides/templates/revealjs.html
  tests/conftest.py
  tests/data/video.mp4
  tests/data/video_data_uri.txt
  tests/test_convert.py
  tests/test_slide.py
Labels: enhancement, html-convert, present, lib

#299 feat(cli): add `next-terminates-loop` CLI option
  CHANGELOG.md
  manim_slides/present/__init__.py
  manim_slides/present/player.py
Labels: present, cli
