Repository jeertmans/manim-slides, pull requests merged in 2023-07, with the labels that each got.

#207 chore(deps): bumping pydantic to V2
  .github/workflows/tests.yml
  .gitignore
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present.py
  manim_slides/slide.py
  poetry.lock
  pyproject.toml
  tests/test_config.py
  tests/test_convert.py
Labels: dependencies

#210 Update index.md
  docs/source/index.md
Labels: documentation

#214 chore(lib): fix typo in warning message
  manim_slides/manim.py
Labels: lib

#215 feat(lib): add wip transition
  manim_slides/manim.py
  manim_slides/slide.py
Labels: enhancement, lib

#216 feat(lib/docs): add sphinx directive
  docs/source/conf.py
  docs/source/reference/api.md
  docs/source/reference/index.md
  docs/source/reference/sphinx_extension.md
  manim_slides/docs/manim_slides_directive.py
  manim_slides/slide.py
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, lib

#217 feat(lib): improve wipe animation
  manim_slides/manim.py
  manim_slides/slide.py
Labels: enhancement, lib

#218 feat(lib): add `wait-time-between-slides` attribute
  docs/source/reference/api.md
  manim_slides/slide.py
Labels: enhancement, lib

#219 feat(lib): add canvas and features
  docs/source/reference/api.md
  manim_slides/slide.py
Labels: enhancement, lib

#222 chore(tests): test commons and defaults
  tests/conftest.py
  tests/test_commons.py
  tests/test_defaults.py
Labels: ci, lib

#223 fix(lib/cli): relative paths, empty slides, and tests
  .gitignore
  manim_slides/config.py
  manim_slides/present.py
  manim_slides/wizard.py
  tests/conftest.py
  tests/slides/BasicExample.json
  tests/slides/files/BasicExample/1413466013_3346521118_223132457.mp4
  tests/slides/files/BasicExample/1413466013_3346521118_223132457_reversed.mp4
  tests/slides/files/BasicExample/1672018281_1369283980_3942561600.mp4
  tests/slides/files/BasicExample/1672018281_1369283980_3942561600_reversed.mp4
  tests/slides/files/BasicExample/1672018281_3136302242_2191168284.mp4
  tests/slides/files/BasicExample/1672018281_3136302242_2191168284_reversed.mp4
  tests/test_config.py
  tests/test_main.py
Labels: bug, ci, lib

#224 feat(lib): change config file from json to toml
  .gitignore
  manim_slides/config.py
  manim_slides/defaults.py
  manim_slides/present.py
  poetry.lock
  pyproject.toml
  tests/test_defaults.py
Labels: enhancement, dependencies, cli, lib

#225 chore(lib): remove all os.path in favor to pathlib
  manim_slides/config.py
  manim_slides/defaults.py
  manim_slides/present.py
  manim_slides/slide.py
  tests/test_defaults.py
Labels: dependencies, lib
