Repository jeertmans/manim-slides, pull requests merged in 2023-03, with the labels that each got.

#141 chore(docs): transparent logo and symbolic link
  README.md
  docs/source/_static/logo.png
  docs/source/_static/logo_dark_docs.png
  docs/source/_static/logo_dark_github.png
  docs/source/_static/logo_dark_transparent.png
  docs/source/_static/logo_light_transparent.png
  docs/source/conf.py
  docs/source/index.md
  static/logo_dark_transparent.png
  static/logo_light_transparent.png
  static/make_logo.sh
Labels: documentation, enhancement

#143 chore(README): add docs badge and update wizard
  README.md
  static/wizard_dark.png
  static/wizard_light.png
Labels: documentation

#142 feat(cli): using cached files when possible
  manim_slides/config.py
Labels: enhancement

#145 chore(docs): adding GUI and HTML documentation pages
  docs/source/_static/wizard_dark.png
  docs/source/_static/wizard_light.png
  docs/source/conf.py
  docs/source/reference/gui.md
  docs/source/reference/html.md
  docs/source/reference/index.md
Labels: documentation, enhancement

#147 chore(lib): reduce import overhead
  manim_slides/__init__.py
  manim_slides/__main__.py
  manim_slides/commons.py
  manim_slides/config.py
  manim_slides/defaults.py
  manim_slides/logger.py
  manim_slides/present.py
  manim_slides/wizard.py
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies

#151 chore(lib): use `next_slide` not `pause`
  docs/source/reference/api.md
  manim_slides/slide.py
Labels: documentation, enhancement

#152 feat(convert): PowerPoint conversion
  docs/source/features_table.md
  docs/source/index.md
  docs/source/reference/sharing.md
  manim_slides/convert.py
  poetry.lock
  pyproject.toml
Labels: enhancement, pptx-convert, cli

#153 chore(deps): remove pkg_resources in favor to importlib
  manim_slides/convert.py
  manim_slides/data/__init__.py
Labels: dependencies

#155 feat(render): support skipping animations
  manim_slides/slide.py
Labels: enhancement, cli

#156 feat(cli): add start at index options
  manim_slides/present.py
Labels: enhancement, cli

#158 feat(cli): auto detect resolution
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present.py
  manim_slides/slide.py
  pyproject.toml
Labels: bug, enhancement, present, cli

#162 fix(cli): do not terminate slides early
  example.py
  manim_slides/present.py
Labels: bug, present

#160 feat(cli/lib): use scene background color as default
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present.py
  manim_slides/slide.py
Labels: enhancement, present
