Repository jeertmans/manim-slides, pull requests merged in 2024-12, with the labels that each got.

#493 fix(ci): actually run tests on multiple Python versions
  .github/workflows/tests.yml
Labels: bug, ci

#495 chore(deps): pin `av<14` to avoid breaking changes
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: dependencies

#497 fix(convert): blank web page when converting multiple slides into HTML
  CHANGELOG.md
  manim_slides/convert.py
  manim_slides/templates/revealjs.html
Labels: bug, html-convert

#482 feat(cli): smarter info window hiding logic
  CHANGELOG.md
  manim_slides/present/__init__.py
  manim_slides/present/player.py
  uv.lock
Labels: enhancement, present, cli

#499 chore(deps): bump ManimGL to 1.7.1
  CHANGELOG.md
  docs/source/faq.md
  docs/source/installation.md
  manim_slides/slide/manimlib.py
  pyproject.toml
  tests/test_checkhealth.py
  tests/test_manim.py
  tests/test_slide.py
  uv.lock
Labels: dependencies
