Repository jeertmans/manim-slides, pull requests merged in 2024-04, with the labels that each got.

#389 feat(cli): added separate option for info window screen
  CHANGELOG.md
  manim_slides/present/__init__.py
  manim_slides/present/player.py
Labels: enhancement, present, cli

#399 chore(docs): add favicon
  CHANGELOG.md
  docs/source/_static/favicon.png
  docs/source/conf.py
  static/favicon.png
  static/logo.py
  static/make_favicon.sh
  static/make_logo.sh
Labels: documentation

#404 chore(docs): add nixpkgs installation documentation
  docs/source/installation.md
Labels: documentation

#412 chore(deps): update RevealJS version to 5.1.0
  manim_slides/convert.py
Labels: bug, enhancement

#415 chore(deps): remove OpenCV python
  manim_slides/convert.py
  pdm.lock
  pyproject.toml
  tests/test_convert.py
Labels: dependencies

#417 chore(ci): checking links and spell checking
  .bumpversion.cfg
  .github/scripts/check_github_issues.py
  .github/workflows/tests.yml
  .mdlc.json
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  docs/source/_static/template.html
  docs/source/contributing/index.md
  docs/source/contributing/workflow.md
  docs/source/index.md
  docs/source/installation.md
  docs/source/quickstart.md
  docs/source/reference/gui.md
  docs/source/reference/html.md
  docs/source/reference/index.md
  docs/source/reference/sharing.md
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present/player.py
  manim_slides/templates/revealjs.html
  manim_slides/utils.py
  paper/paper.md
  pyproject.toml
Labels: documentation, ci

#418 chore(docs): add faq page
  CHANGELOG.md
  README.md
  docs/source/faq.md
  docs/source/index.md
Labels: documentation

#419 fix(cli): broken `--show-config` command
  CHANGELOG.md
  docs/source/faq.md
  manim_slides/convert.py
Labels: bug, cli

#420 chore(dev): move to Rye instead of PDM
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .python-version
  CHANGELOG.md
  docs/source/contributing/workflow.md
  docs/source/installation.md
  docs/source/manim_or_manimgl.md
  docs/source/reference/magic_example.ipynb
  manim_slides/__init__.py
  manim_slides/config.py
  manim_slides/convert.py
  manim_slides/present/__init__.py
  manim_slides/present/player.py
  manim_slides/render.py
  manim_slides/slide/animation.py
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  manim_slides/slide/manimlib.py
  manim_slides/utils.py
  pdm.lock
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  static/make_favicon.sh
  static/make_logo.sh
  tests/conftest.py
  tests/test_base_slide.py
  tests/test_manim.py
  tests/test_present.py
  tests/test_slide.py
  tests/test_utils.py
Labels: bug, ci

#422 chore(docs): add an Examples Gallery
  CHANGELOG.md
  docs/source/gallery.md
  docs/source/index.md
Labels: documentation

#423 feat(lib): add options for skipping Sphinx directive
  CHANGELOG.md
  manim_slides/docs/manim_slides_directive.py
Labels: documentation, lib
