Repository jeertmans/manim-slides, pull requests merged in 2025-01, with the labels that each got.

#506 fix(deps): bump ManimGL>=1.7.2
  .github/workflows/tests.yml
  CHANGELOG.md
  custom_config.yml
  manim_slides/render.py
  manim_slides/slide/manimlib.py
  pyproject.toml
  tests/test_slide.py
  uv.lock
Labels: bug, dependencies

#485 feat(cli): document config options
  CHANGELOG.md
  docs/source/conf.py
  docs/source/reference/cli.md
  manim_slides/convert.py
  manim_slides/templates/revealjs.html
  pyproject.toml
  tests/test_convert.py
  uv.lock
Labels: enhancement, html-convert, pptx-convert, cli, pdf-convert

#505 feat(convert/html): inline CSS and JS with convert --one_file --offline
  CHANGELOG.md
  docs/source/_static/template.html
  docs/source/faq.md
  docs/source/reference/sharing.md
  manim_slides/convert.py
  manim_slides/ipython/ipython_magic.py
  manim_slides/templates/revealjs.html
  tests/test_convert.py
  tests/test_main.py
Labels: enhancement, html-convert, cli

#507 fix(docs): dead links
  docs/source/gallery.md
Labels: documentation

#518 chore(ci): fix RTD build
  .python-version
  .readthedocs.yaml
  pyproject.toml
  uv.lock
Labels: documentation, ci

#516 feat(lib): add `skip_animations` compatibility
  CHANGELOG.md
  manim_slides/config.py
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  tests/test_slide.py
  uv.lock
Labels: enhancement, lib

#522 fix(lib): bump Manim and fix OpenGL renderer
  CHANGELOG.md
  example.py
  manim_slides/slide/manim.py
  pyproject.toml
  tests/test_slide.py
  uv.lock
Labels: bug, lib, manimce

#523 feat(lib): add `start_skip_animations` and `stop_skip_animations` meth.
  CHANGELOG.md
  docs/source/reference/api.md
  manim_slides/slide/base.py
  tests/test_base_slide.py
  tests/test_slide.py
Labels: enhancement, lib

#524 fix(lib): pass skip argument to ManimCE
  CHANGELOG.md
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  tests/test_base_slide.py
  uv.lock
Labels: bug, lib

#439 feat(lib): smarter files reversing
  CHANGELOG.md
  manim_slides/slide/base.py
  manim_slides/slide/manim.py
  manim_slides/utils.py
  tests/test_slide.py
  uv.lock
Labels: enhancement, help wanted, lib

#443 chore(convert): improve HTML Jinja2 template
  CHANGELOG.md
  docs/source/_static/template.html
  manim_slides/convert.py
  manim_slides/templates/revealjs.html
  pyproject.toml
  uv.lock
Labels: enhancement, html-convert
